mkdir -p ./submission
cp Arena.m ./submission/Arena.m
cp Block.m ./submission/Block.m
cp Camera.m ./submission/Camera.m
cp feetToInches.m ./submission/feetToInches.m
cp inchesToFeet.m ./submission/inchesToFeet.m
cp main.m ./submission/main.m
cp proposal.pdf ./submission/proposal.pdf
cp randMinMax.m ./submission/randMinMax.m
cp Robot.m ./submission/Robot.m
cp SimulationParameters.m ./submission/SimulationParameters.m
cp squareVertices.m ./submission/squareVertices.m
cp write-up.pdf ./submission/gewitteman-writeup.pdf
